# Generated by Django 5.1.6 on 2025-02-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='upload/user_profile_images/')),
                ('source', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('destination', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('current_balance', models.FloatField(default=0.0)),
                ('deducted_balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
