# Generated by Django 5.1.6 on 2025-02-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
